server:
  port: 8001

eureka:
  instance:
    hostname: dengfeng1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://dengfeng1:8001/eureka/
      #defaultZone: http://dengfeng2:8002/eureka/,http://dengfeng3:8003/eureka/
